### PR TITLE
Add reload mechanism (taken from bottle)

### PR DESCRIPTION
**Pull request by leiserfg**

### CODE REVIEW

**Comment by leiserfg** [comment]
It should fix #43

**Comment by timothycrosley** [comment]
@leiserfg This looks fantastic! The only thing missing now is full coverage, would you like to take care of that or would you like me to post merge?

Either way thanks for the great work!

~Timothy

**Comment by timothycrosley** [comment]
Thanks!

**Comment by timothycrosley** [comment]
Looks great! Thanks!

**Pull request merged**
