### PR TITLE
Added generic Authorization header check. A practical example using P…

### PR DESCRIPTION
**Pull request by johnlam**
Just added a check for an Authorization header and created an example using [PyJWT](https://github.com/jpadilla/pyjwt) token generationa and verification. If you don't like that dependency , I could make an example using HMAC+SHA256 but I think it's far more realistic to showcase JWT. Relevant tests included.

### CODE REVIEW

**Comment by timothycrosley** [comment]
HI @johnlam, thanks for the work! I don't see how this should add a dependency to hug istelf though? It looks like just simply moving the requirement to https://github.com/timothycrosley/hug/blob/develop/requirements/build.txt which is used when running tests only, you could fix that issue. Once this is done I will be very happy to merge in the pull request.

Thanks!

~Timothy

**Comment by johnlam** [comment]
Thanks for the recommendation, I had a broken dev setup. Hopefully this will fix it.

**Comment by timothycrosley** [comment]
Looks great now! Thanks for the awesome contribution!

**Comment by zhwei820** [comment]
Awesome !! thanks!

**Pull request merged**
