### PR TITLE
Distribute tests on all CPU cores

### PR DESCRIPTION
**Pull request by vortec**
This PR uses pytest-xdist to execute the unit tests in parallel and is configured to make use of all the available CPU cores. On my machine this made the tests run in 3 instead of 12 seconds.

### CODE REVIEW

**Comment by timothycrosley** [comment]
+1 This is awesome

**Comment by vortec** [comment]
Seems there are race conditions in the tests! I will investigate further tomorrow!

**Comment by vortec** [comment]
As discussed earlier, this is hard for me to fix. The test code must be refactored (using fixtures?) so that global state is avoided.

**Comment by vortec** [comment]
Did #288 fix this aswell and is the one failed OSX build related to something different? Or still broken?

**Comment by timothycrosley** [comment]
Hi @vortec!

OSX builds in general now work fine, however we still haven't gotten parallel builds working on any system, as it requires significant refactoring work to the test suite.

Thanks!

~Timothy

**Comment by timothycrosley** [comment]
Closing this as support was implemented in a different pull request, thanks!

**Pull request closed without merging**
