### PR TITLE
Added docker-compose environment along with instructions in README.md

### PR DESCRIPTION
**Pull request by housni**
@timothycrosley, Hug is such a great framework. I'm new to Hug and to Python but I do all my other development in Docker and wanted to add more functionality to your Docker files.

Being new to Python, I'm not sure if I've omitted something in my Dockerfiles but if you think this is good enough to merge but needs further changes, let me know and I'll try and make those changes.

Keep up the good work!

### CODE REVIEW

**Comment by vortec** [comment]
Thanks for your work @housni, I do see a couple of issues with this PR though.

- It forces users to clone the entire hug repository when all they need is the `docker` directory. In `docker/gunicorn/Dockerfile`, hug gets installed from PyPI and the rest of the cloned source code is just there without any effect on the resulting Docker containers. For end users, who are not interested in the development process of hug, I think it's better to offer official hug images on Docker Hub and not force them to clone the Git repository. I've written down some thoughts regarding this approach here: https://github.com/timothycrosley/hug/issues/194#issuecomment-199008163
- `docker/gunicorn/Dockerfile` assumes that the end user's API exposes `__hug_wsgi__` on package level. This should be configurable or at least mentioned in the docs.
- `README.md` assumes that `docker-machine` is installed on Windows and Mac. There's Docker for Mac and Docker for Windows now, which use OS virtualization and don't come with `docker-machine` anymore.
- I'm not sure if the `workspace` container is needed? Can't you just mount the volume into the `gunicorn` container?
- In `docker/workspace/Dockerfile`, why do you need this command? `sed -i -e "s/bin\/ash/bin\/bash/" /etc/passwd` 

Apart from these things I really appreciate more work being done making hug more accessible for all kinds of users.

**Comment by housni** [comment]
Hi @vortec,

- Ah, if you're planning on creating a separate Dockerfile for Dockerhub, that works fine too. I just thought I'd augment something that was already part of the repo since I work on Docker for everything but what you're saying makes sense from a development only perspective. My only qualms about a single Docker image is that it breaks the general principle of Docker because it encourages users to have one process per container. Therefore, I typically use Docker Compose to spin up a db, webserver and a workspace container and link them together. That makes it easier to move it to a production ready status, if I want to. But I agree with you that having this in the repo is a bad idea given that people may install this via PyPI. It something that I didn't even consider.
- Not sure what you mean here. I'm new to Python. Should this not be the case? I just used the Quickstart instructions.
- Unfortunately, I don't have a Windows and Mac to test on. If we do end up deciding going ahead with this for some reason, perhaps someone would help me test on these platforms.
- `workspace` exists in the interest of keeping to the Docker philosophy of having one process per container. Gunicorn would run on the `gunicorn` container while our dev tools would exist on the `workspace` container.
- I'm using Alpine Linux as the base image which uses the Almquist Shell. That line replaces references to Almquist Shell with the Bash Shell so that users will have a bash shell on login. That's actually a matter of personal preference.

**Comment by timothycrosley** [comment]
Thanks for putting this together! There are def somethings that can be improved per @vortec's feedback, but this is an excellent starting point for further pull requests to be put together

Thanks!

~Timothy

**Comment by housni** [comment]
I'll be happy to contribute, especially if someone can clarify @vortec's following point:

> docker/gunicorn/Dockerfile assumes that the end user's API exposes __hug_wsgi__ on package level. This should be configurable or at least mentioned in the docs.

**Comment by vortec** [comment]
It's no biggie. I just mean that `__hug_wsgi__`, the Python variable name from the quickstart tutorial, should be configurable.

**Pull request merged**
