### PR TITLE
Ensure that api_version is a number

### PR DESCRIPTION
**Pull request by banteg**
See #418

### CODE REVIEW

**Comment by thedrow** [comment]
Many people would want to specify the API version with a 'v' prefix.
I don't think this PR should be accepted.

Also, it'd be really surprising when someone specifies an API version and then hug silently ignores it. I think that at least we should raise an error here if this PR is merged after all.

**Comment by banteg** [comment]
I agree that API version should not be limited to integers, but that's how it works in hug now (see changed line) and this pull request doesn't break it, it just fixes the weird bug with routes like `/{arg}` starting with a letter v (see https://github.com/timothycrosley/hug/issues/418).

**Comment by ovnicraft** [comment]
Maybe could be validated with regexp to allow versioning api `/vMajor.Minor/`
Useful link: http://stackoverflow.com/questions/389169/best-practices-for-api-versioning

**Comment by philipaconrad** [comment]
This PR really ought to be merged. Folks can throw up a new PR when the `hug` community can decide on what a "right way to do URL versioning" should look like. The bug this PR solves is straightforward, and is a case of something being _really_ broken in the library.

FYI, I actually do need to be able to start some URLs with a 'v', and it's more than a little ridiculous that I can't do that right now in `hug` without invoking strange behaviors.

**Comment by timothycrosley** [comment]
Thanks for getting this prepared I agree 100% with this change, and apologize for not merging it sooner

~Timothy

**Pull request merged**
