### PR TITLE
Fix deprecation warnings due to invalid escape sequences and comparison of literals using is.

### LINKED ISSUE #867: Deprecation warning due to invalid escape sequences
Deprecation warnings are raised due to invalid escape sequences. This can be fixed by using raw strings or escaping the literals. pyupgrade also helps in automatic conversion : https://github.com/asottile/pyupgrade/

```
find . -iname '*.py' | grep -Ev 'vendor|example|doc|tools|sphinx' | xargs -P4 -I{} python3.8 -Wall -m py_compile {}
./tests/test_output_format.py:371: SyntaxWarning: "is" with a literal. Did you mean "=="?
  assert 9 is hug.output_format._json_converter(ex_int)
./tests/test_output_format.py:414: SyntaxWarning: "is" with a literal. Did you mean "=="?
  assert 1 is hug.output_format._json_converter(np_type(1))
./hug/middleware.py:171: DeprecationWarning: invalid escape sequence \d
  reqpath = re.sub("^(/v\d*/?)", "/", reqpath)
./hug/use.py:185: DeprecationWarning: invalid escape sequence \d
  status_code = int("".join(re.findall("\d+", response.status)))
./hug/api.py:41: DeprecationWarning: invalid escape sequence \#
  INTRO = """
```

### PR DESCRIPTION
**Pull request by tirkarthi**
Fixes #867

### CODE REVIEW

**Review by akaihola — APPROVED** [review]
All of these changes look correct to me.

**Comment by tirkarthi** [comment]
Thanks @akaihola . CI error seems unrelated to this PR.

**Comment by akaihola** [comment]
Indeed, [the CI test failure](https://ci.appveyor.com/project/TimothyCrosley/hug-s7p6r/builds/34294473) seems to be due to a timed out UDP request to a local test server.

**Comment by timothycrosley** [comment]
Thank you!

**Comment by tirkarthi** [comment]
Thanks @timothycrosley and @akaihola  :)

**Pull request merged**
